### ISSUE TITLE
[react-emotion-theme]emotion template literal theme color support

### ISSUE THREAD

**Issue by vchoisk** [daangn/karrot-ui#24]
지금 구현에서 template literal을 활용할때,

```
const Button = styled.button`
  color: $carrot500;
`
```

요렇게 color palette 사용하는것이 가능한가요?

혹은 아래와 같이 emotion theme을 활용해야만 하나요?
```
const Button = styled.button`
  color: ${({props}) => props.theme.colors.carrot500};
`
```

**Comment by cometkim** [comment]
Emotion 의 경우 emotion theming 공식을 따릅니다.

별도로 사용하고 싶은 경우 CSS Variable 을 정의해서 사용하는 것은 가능합니다.

```tsx
const Button = styled.button`
  color: var(--carrot500);
`

// ...

<Container style={{ '--carrot500': '#...' }}>
  <Button />
</Container>

```

design-token 에서 미리 정의된 스타일 시트를 제공하고 있어서 이걸 써도 됩니다.

https://github.com/daangn/karrot-ui/blob/main/packages/design-token/README.md#css-css-loader

**Comment by vchoisk** [comment]
말씀해주신데로 design-token을 활용해서 하는 것을 고려하다가, `react-emotion-theme` 자체적으로 지원하도록 수정하면 어떨까 싶었어요 ㅎㅎㅎ

하지만 emotion theming 공식을 벗어나는것이라면 프로젝트별로 필요시에 섞어서 쓰는것으로 해야겠네요 ㅎㅎ

이슈는 닫을게요!
