### ISSUE TITLE
Can't import the named export 'Fragment' from non EcmaScript module

### ISSUE THREAD

**Issue by tonyfromundefined** [daangn/karrot-ui#34]
```
../.yarn/__virtual__/@karrotmarket-react-emotion-theme-virtual-077c91d7ca/0/cache/@karrotmarket-react-emotion-theme-npm-1.0.1-d12bf8e42a-6a84a44cfa.zip/node_modules/@karrotmarket/react-emotion-theme/lib/index.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
```

react-emotion-theme@1.0.1 is not working in create-react-app. (webpack v4)

<img width="1122" alt="스크린샷 2021-11-05 오후 8 19 09" src="https://user-images.githubusercontent.com/20325202/140502873-9582d050-c1f0-44da-9c50-d46e1c31e402.png">

**Comment by cometkim** [comment]
이거 시도해보실 수 있을까용 https://github.com/formatjs/formatjs/issues/1395#issuecomment-518823361

BTW, 이제 Webpack 4 는 명시적으로 지원하지 않기로...

**Comment by tonyfromundefined** [comment]
Workaround: https://github.com/daangn/nearby/pull/84

**Comment by cometkim** [comment]
🤔 🤔 

Webpack 4 문제가 맞으므로 이슈는 close 합니다.
